Repository ubigu/kartalla, pull requests merged in 2025-01, with the labels that each got.

#65 Trying to fix site name problems in Google
  client/index.html
Labels: fix

#66 Add organization user roles
  client/src/components/admin/EditSurvey.tsx
  client/src/components/admin/SurveyListItem.tsx
  client/src/stores/UserContext.tsx
  interfaces/user.d.ts
  server/migrations/1735883813848_user-roles.ts
  server/src/application/survey.ts
  server/src/auth/azure.ts
  server/src/auth/google-oauth.ts
  server/src/auth/index.ts
  server/src/user.ts
Labels: feature

#67 Add super user role
  client/src/components/admin/AppBarUserMenu.tsx
  client/src/components/admin/EditSurvey.tsx
  client/src/components/admin/SurveyImageList.tsx
  client/src/components/admin/SurveyListItem.tsx
  client/src/stores/UserContext.tsx
  server/src/application/survey.ts
  server/src/auth/index.ts
  server/src/openapi/openapi.yaml
  server/src/routes/file.routes.ts
  server/src/routes/survey.routes.ts
  server/src/user.ts
Labels: feature

#68 Fix super user file upload
  client/src/components/admin/FileUpload.tsx
  server/src/auth/index.ts
Labels: fix

#69 Add user id to morgan logs
  server/src/app.ts
Labels: chore

#70 Feature/data encryption
  e2e/server.env
  server/.template.env
  server/migrations/1736504593192_encrypt-users.ts
  server/src/database.ts
  server/src/user.ts
Labels: feature

#71 Import the encryption key via environment variables
  server/migrations/1736504593192_encrypt-users.ts
Labels: fix

#72 Feature/delete restrictions
  client/src/components/admin/EditSurveyControls.tsx
  client/src/components/admin/EditSurveyHeader.tsx
  client/src/components/admin/EditSurveyPage.tsx
  client/src/components/admin/Instructions/AppBarInstructionsMenu.tsx
  client/src/components/icons/HelpCircleIcon.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  server/migrations/1737009588404_answer-entry-delete-restrict.ts
  server/src/application/survey.ts
  server/src/routes/survey.routes.ts
Labels: feature

#73 Enable publishing survey submissions via API
  client/src/components/admin/DataPublish.tsx
  client/src/components/admin/SubmissionsPage/SurveySubmissionsPage.tsx
  client/src/components/icons/HierarchyIcon.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  server/migrations/1736241832049_add-publications-table.ts
  server/src/application/answer.ts
  server/src/application/submission.ts
  server/src/application/survey.ts
  server/src/auth/index.ts
  server/src/openapi/openapi.yaml
  server/src/routes/survey.routes.ts
Labels: feature

#77 Feature/user management
  client/src/components/admin/AdminApplication.tsx
  client/src/components/admin/AppBarUserMenu.tsx
  client/src/components/admin/ProtectedRoute.tsx
  client/src/components/admin/UserManagement/NewUserRequest.tsx
  client/src/components/admin/UserManagement/UserList.tsx
  client/src/components/admin/UserManagement/index.tsx
  client/src/components/icons/UserAddSmallIcon.tsx
  client/src/stores/UserContext.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  docker-compose.email.yml
  docker-compose.yml
  interfaces/user.d.ts
  server/.template.env
  server/email-templates/new-user/html.pug
  server/email-templates/new-user/style.css
  server/email-templates/new-user/subject.pug
  server/email-templates/new-user/text.pug
  server/migrations/1737713297936_user-status.ts
  server/src/auth/index.ts
  server/src/email/email.ts
  server/src/routes/user.routes.ts
  server/src/translations/en.json
  server/src/translations/fi.json
  server/src/translations/se.json
  server/src/user.ts
Labels: feature

#78 Add dependabot configs
  .github/dependabot.yml
Labels: chore

#74 Add personal info questions for surveys
  .github/dependabot.yml
  client/.eslintrc
  client/src/components/PersonalInfoQuestion.tsx
  client/src/components/SurveyQuestion.tsx
  client/src/components/admin/AddSurveySectionActions.tsx
  client/src/components/admin/AppBarUserMenu.tsx
  client/src/components/admin/DataExport.tsx
  client/src/components/admin/DataPublish.tsx
  client/src/components/admin/EditPersonalInfoQuestion.tsx
  client/src/components/admin/EditSurveyEmail.tsx
  client/src/components/admin/SubmissionsPage/AnswersList.tsx
  client/src/components/admin/SubmissionsPage/PageQuestionList.tsx
  client/src/components/admin/SubmissionsPage/SurveySubmissionsPage.tsx
  client/src/components/admin/SurveySectionAccordion/SurveySectionAccordion.tsx
  client/src/stores/SurveyAnswerContext.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  interfaces/submission.d.ts
  interfaces/survey.d.ts
  server/migrations/1738057867468_submission-personal-info.ts
  server/src/application/answer.ts
  server/src/application/pdf-generator.ts
  server/src/application/submission.ts
  server/src/application/survey.ts
  server/src/openapi/openapi.yaml
  server/src/routes/answers.routes.ts
  server/src/routes/published-survey.routes.ts
  server/src/routes/survey.routes.ts
  server/src/translations/en.json
  server/src/translations/fi.json
  server/src/translations/se.json
  server/src/utils.ts
Labels: feature

#94 Fix/personal info
  client/src/components/PersonalInfoQuestion.tsx
  client/src/components/admin/UserManagement/NewUserRequest.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  server/src/application/submission.ts
  server/src/routes/survey.routes.ts
Labels: fix

#95 Fix answer view map and survey follow up section deletion bug
  client/src/components/admin/AdminMap.tsx
  client/src/components/admin/SubmissionsPage/AnswerMap.tsx
  client/src/components/admin/SurveyListItem.tsx
  client/src/components/admin/SurveySectionAccordion/FollowUpSectionMenu.tsx
  server/src/application/survey.ts
Labels: fix

#96 Minor bug fixes and accessibility improvements
  client/src/components/MatrixQuestion.tsx
  client/src/components/admin/SurveyListItem.tsx
  server/src/application/survey.ts
Labels: fix
