Repository ubigu/kartalla, pull requests merged in 2025-02, with the labels that each got.

#100 Add general notifications feature
  client/src/components/RichTextEditor.tsx
  client/src/components/admin/AdminAppBar.tsx
  client/src/components/admin/AdminApplication.tsx
  client/src/components/admin/GeneralNotification/EditGeneralNotification.tsx
  client/src/components/admin/GeneralNotification/GeneralNotificationList.tsx
  client/src/components/admin/GeneralNotification/GeneralNotificationNavigationButton.tsx
  client/src/components/admin/GeneralNotification/index.tsx
  client/src/components/icons/MegaphoneIcon.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  client/src/themes/common.ts
  interfaces/generalNotification.d.ts
  server/migrations/1738570528007_general-notifications.ts
  server/package-lock.json
  server/package.json
  server/src/application/generalNotification.ts
  server/src/routes/generalNotification.routes.ts
  server/src/routes/index.ts
  server/src/routes/user.routes.ts
Labels: feature

#102 Improve styling
  client/src/components/SurveyQuestion.tsx
  client/src/components/admin/AdminAppBar.tsx
  client/src/components/admin/ConditionRow.tsx
  client/src/components/admin/EditSurveyPageConditions.tsx
  client/src/components/admin/QuestionOptions.tsx
  client/src/components/admin/SurveyListItem.tsx
  client/src/stores/SurveyMapContext.tsx
  client/src/stores/SurveyThemeProvider.tsx
  client/src/themes/admin.ts
  client/src/themes/common.ts
  client/src/themes/survey.ts
Labels: feature

#103 Fix survey submission error
  server/src/application/submission.ts
Labels: fix

#104 Fix file saving and improve submissions map geometries
  client/src/components/admin/SubmissionsPage/OskariMap.tsx
  server/src/application/survey.ts
Labels: fix

#106 Chore/new e2e tests
  .github/workflows/pr-test.yml
  client/src/components/MatrixQuestion.tsx
  client/src/components/MultiMatrixQuestion.tsx
  client/src/components/PersonalInfoQuestion.tsx
  client/src/components/SortingQuestion.tsx
  client/src/components/SurveyQuestion.tsx
  client/src/components/SurveyStepper.tsx
  client/src/components/admin/ColorSelect.tsx
  client/src/components/admin/EditGroupedCheckBoxQuestion.tsx
  client/src/components/admin/EditMatrixQuestion.tsx
  client/src/components/admin/EditMultiMatrixQuestion.tsx
  client/src/components/admin/EditSurveyInfo.tsx
  client/src/components/admin/SurveySectionAccordion/FollowUpSectionAccordion.tsx
  client/src/components/admin/SurveySectionAccordion/SectionDetails.tsx
  client/src/components/admin/SurveySectionAccordion/SurveySectionAccordion.tsx
  client/src/components/admin/ThemeSelect.tsx
  client/src/themes/common.ts
  e2e/package-lock.json
  e2e/package.json
  e2e/pages/adminPage.ts
  e2e/pages/surveyEditPage.ts
  e2e/playwright.config.ts
  e2e/tests/questions/checkBoxQuestion.test.ts
  e2e/tests/questions/radioQuestion.test.ts
  e2e/tests/survey.test.ts
  e2e/utils/data.ts
  e2e/utils/db.ts
  e2e/utils/fixtures.ts
  package-lock.json
  server/migrations/1739287388688_new-theme-colors.ts
Labels: chore

#108 Fix/map and general notification fixes
  .github/workflows/pr-test.yml
  client/src/components/MapQuestion.tsx
  client/src/components/SurveyStepper.tsx
  client/src/components/admin/AdminFrontPage.tsx
  client/src/components/admin/GeneralNotification/EditGeneralNotification.tsx
  client/src/components/admin/GeneralNotification/GeneralNotificationList.tsx
  client/src/components/admin/GeneralNotification/index.tsx
  client/src/components/admin/SurveyList.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  server/src/application/generalNotification.ts
Labels: fix

#109 Fix survey map answering bug on iPhones
  client/src/components/MapQuestion.tsx
  client/src/components/SurveyQuestion.tsx
Labels: fix

#110 Add timeout to fix iphone map answering bug
  client/src/components/MapQuestion.tsx
Labels: fix

#112 Add version info dialog
  .github/workflows/ci.yml
  client/src/components/admin/Instructions/AppBarInstructionsMenu.tsx
  client/src/components/admin/VersionInfoDialog.tsx
  client/src/components/icons/UbiguLogoWhite.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  client/src/themes/common.ts
  client/vite.config.ts
  client/vite.d.ts
Labels: feature

#117 Update minor deps and remove redundant console.log
  client/package-lock.json
  client/package.json
  client/src/components/admin/VersionInfoDialog.tsx
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: chore

#120 Feature/UI improvements
  client/src/components/SurveyStepper.tsx
  client/src/components/admin/SurveyList.tsx
Labels: feature

#116 Fix/file copy on section paste
  client/src/components/admin/AddSurveySectionActions.tsx
  client/src/components/admin/EditSurveySideBar.tsx
  client/src/controllers/AdminFileController.ts
  interfaces/survey.d.ts
  server/src/application/survey.ts
  server/src/routes/file.routes.ts
  server/src/routes/survey.routes.ts
Labels: fix

#122 Fix/bug fixes and refactoring
  .github/workflows/ci.yml
  client/admin/index.html
  client/package-lock.json
  client/package.json
  client/src/components/admin/FileUpload.tsx
  client/src/components/admin/GeneralNotification/GeneralNotificationNavigationButton.tsx
  client/src/components/admin/GeneralNotification/index.tsx
  client/src/stores/en.json
  client/src/stores/fi.json
  client/src/stores/se.json
  docker-compose.yml
  e2e/docker-compose.yml
  e2e/server.env
  e2e/utils/db.ts
  server/.template.env
  server/package.json
  server/src/application/survey.ts
  server/src/routes/generalNotification.routes.ts
  server/src/routes/survey.routes.ts
Labels: fix
